# Generated by Django 5.1.2 on 2024-10-15 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='время последнего изменения')),
                ('email', models.EmailField(max_length=100, verbose_name='email')),
                ('country', models.CharField(max_length=100, verbose_name='страна')),
                ('city', models.CharField(max_length=100, verbose_name='город')),
                ('street', models.CharField(max_length=100, verbose_name='улица')),
                ('office', models.CharField(max_length=100, verbose_name='номер дома')),
            ],
            options={
                'verbose_name': 'контакт',
                'verbose_name_plural': 'контакты',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='время последнего изменения')),
                ('name', models.CharField(max_length=100, verbose_name='наименование')),
                ('model', models.CharField(max_length=100, verbose_name='модель продукта')),
                ('release_date', models.DateField(help_text='ДД.ММ.ГГГГ', verbose_name='дата выпуска')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
            },
        ),
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='время последнего изменения')),
                ('name', models.CharField(max_length=100)),
                ('contacts', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='chain.contacts')),
                ('products', models.ManyToManyField(to='chain.products')),
            ],
            options={
                'verbose_name': 'завод',
                'verbose_name_plural': 'заводы',
            },
        ),
        migrations.CreateModel(
            name='Retailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='время последнего изменения')),
                ('name', models.CharField(max_length=100)),
                ('debt', models.FloatField(blank=True, default=0.0, null=True, verbose_name='задолженность')),
                ('contacts', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='retailer', to='chain.contacts')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retailers', to='chain.factory')),
                ('products', models.ManyToManyField(to='chain.products')),
                ('provider_factory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_retailers', to='chain.factory')),
                ('provider_retailer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_retailers', to='chain.retailer')),
            ],
            options={
                'verbose_name': 'розничная сеть',
                'verbose_name_plural': 'розничные сети',
            },
        ),
        migrations.CreateModel(
            name='Trader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='время последнего изменения')),
                ('name', models.CharField(max_length=100)),
                ('debt', models.FloatField(blank=True, default=0.0, null=True, verbose_name='задолженность')),
                ('contacts', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trader', to='chain.contacts')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traders', to='chain.factory')),
                ('products', models.ManyToManyField(to='chain.products')),
                ('provider_factory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_traders', to='chain.factory')),
                ('provider_retailer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_traders', to='chain.retailer')),
                ('provider_trader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_traders', to='chain.trader')),
            ],
            options={
                'verbose_name': 'индивидуальный предприниматель',
                'verbose_name_plural': 'индивидуальные предприниматели',
            },
        ),
        migrations.AddField(
            model_name='retailer',
            name='provider_trader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_retailers', to='chain.trader'),
        ),
    ]
