# Generated by Django 5.1.2 on 2024-10-15 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retailer',
            name='factory',
        ),
        migrations.RemoveField(
            model_name='trader',
            name='factory',
        ),
        migrations.AddField(
            model_name='factory',
            name='debt',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='задолженность'),
        ),
    ]
