# Generated by Django 5.1.2 on 2024-10-16 09:51

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0004_alter_factory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trader',
            name='debt',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='задолженность'),
        ),
    ]
