# Generated by Django 5.1.2 on 2024-10-16 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0005_alter_trader_debt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts',
            old_name='office',
            new_name='house_number',
        ),
    ]
